CREATE TABLE SECURITY_PERMISSIONS (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT PERMISSIONS_NAME_UQ UNIQUE(NAME)
);

CREATE TABLE SECURITY_ROLE_PERMISSIONS (
    ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_ID       BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL
);

CREATE TABLE SECURITY_ROLES (
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    CONSTRAINT ROLES_NAME_UQ UNIQUE(NAME)
);

CREATE TABLE SECURITY_SUBJECT_ROLES (
    ID         BIGINT AUTO_INCREMENT PRIMARY KEY,
    SUBJECT_ID BIGINT NOT NULL,
    ROLE_ID    BIGINT NOT NULL
);

CREATE TABLE SECURITY_SUBJECTS (
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME  VARCHAR(255) NOT NULL,
    PASSWORD  VARCHAR(255) NOT NULL,
    SALT      VARCHAR(255) NOT NULL,
    ENABLED   BOOLEAN,
    USER_ID   BIGINT,
    CONSTRAINT SUBJECTS_USERNAME_UQ UNIQUE(USERNAME)
);

CREATE TABLE USERS
(
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    PAY_NUMBER         VARCHAR(20)    NOT NULL,
    NAME               VARCHAR(256)   NOT NULL,
    EMAIL              VARCHAR(256)   NOT NULL UNIQUE,
    MANAGER_ID         BIGINT,
    CREATED_BY_SUBJECT BIGINT,
    CREATION_DATE      TIMESTAMP      NOT NULL,
    IS_MANAGER         VARCHAR(1)     NOT NULL CHECK (IS_MANAGER IN ('Y', 'N')),
    PHONE_NUMBER       VARCHAR(50),
    MOBILE_NUMBER      VARCHAR(50),
    ORGANISATION       VARCHAR(100),
    JOB_TITLE          VARCHAR(256),
    DEPARTMENT         VARCHAR(256),
    ADDRESS            VARCHAR(2000),
    LOCATION           VARCHAR(100),
    LICENCE            VARCHAR(2000)
);