INSERT INTO SECURITY_ROLES (NAME, DESCRIPTION)
VALUES ('admin', 'Admin Role');

INSERT INTO SECURITY_ROLES (NAME, DESCRIPTION)
VALUES ('doNothing', 'This guy can do nothing');

INSERT INTO SECURITY_ROLES (NAME, DESCRIPTION)
VALUES ('drawingViewer', 'Allows drawing viewing only');

INSERT INTO SECURITY_PERMISSIONS(NAME, DESCRIPTION)
VALUES('*', 'All permissions');

INSERT INTO SECURITY_PERMISSIONS(NAME, DESCRIPTION)
VALUES('view:drawing:*', 'All view drawing permissions');

INSERT INTO SECURITY_PERMISSIONS(NAME, DESCRIPTION)
VALUES('view:drawing:info', 'Only view drawing info permissions');

INSERT INTO SECURITY_ROLE_PERMISSIONS(PERMISSION_ID, ROLE_ID)
SELECT P.ID PERMISSION_ID, R.ID ROLE_ID FROM SECURITY_ROLES R, SECURITY_PERMISSIONS P WHERE R.NAME = 'admin' AND P.NAME = '*';

INSERT INTO SECURITY_ROLE_PERMISSIONS(PERMISSION_ID, ROLE_ID)
SELECT P.ID PERMISSION_ID, R.ID ROLE_ID FROM SECURITY_ROLES R, SECURITY_PERMISSIONS P WHERE R.NAME = 'drawingViewer' AND P.NAME = 'view:drawing:*';

INSERT INTO USERS(PAY_NUMBER, NAME, EMAIL, CREATION_DATE, IS_MANAGER, PHONE_NUMBER, ORGANISATION, JOB_TITLE, DEPARTMENT, ADDRESS, LOCATION, LICENCE)
VALUES('123456', 'Admin User', 'admin@email.com', PARSEDATETIME('17-10-2014 13:00:11.00', 'dd-MM-yyyy hh:mm:ss.SS'), 'N', '01383 412131', 'Babcock', 'Administrator', 'IT', 'Rosyth Dockyard', 'Rosyth', 'Admin licence');

INSERT INTO USERS(PAY_NUMBER, NAME, EMAIL, CREATION_DATE, IS_MANAGER, PHONE_NUMBER, ORGANISATION, JOB_TITLE, DEPARTMENT, ADDRESS, LOCATION, LICENCE)
VALUES('234567', 'Jill Document', 'jd@email.com', PARSEDATETIME('12-03-2016 11:00:44.69', 'dd-MM-yyyy hh:mm:ss.SS'), 'N', '01383 412131', 'Babcock', 'Document Controller', 'Doc Control', 'Rosyth Dockyard', 'Rosyth', 'DC1 licence');

INSERT INTO USERS(PAY_NUMBER, NAME, EMAIL, CREATION_DATE, IS_MANAGER, PHONE_NUMBER, ORGANISATION, JOB_TITLE, DEPARTMENT, ADDRESS, LOCATION, LICENCE)
VALUES('876543', 'Bobby D. Nothing', 'bdn@email.com', PARSEDATETIME('27-11-2017 09:12:52.22', 'dd-MM-yyyy hh:mm:ss.SS'), 'N', '01383 412131', 'Babcock', 'FLM', 'Marine', 'Rosyth Dockyard', 'Rosyth', 'No licence');

INSERT INTO SECURITY_SUBJECTS(USERNAME, PASSWORD, SALT, ENABLED, USER_ID)
SELECT 'admin', 'tiasHslWV7/ieEwGxos3LkNKvZLd/ben0qI3xXJrgjs=', 'pOijUhjnLLpoiyTTSeWq', 1, ID FROM USERS WHERE NAME = 'Admin User';

INSERT INTO SECURITY_SUBJECT_ROLES(SUBJECT_ID, ROLE_ID)
SELECT SS.ID, SR.ID  FROM SECURITY_ROLES SR, SECURITY_SUBJECTS SS WHERE SR.NAME = 'admin' AND SS.USERNAME = 'admin';

INSERT INTO SECURITY_SUBJECTS(USERNAME, PASSWORD, SALT, ENABLED, USER_ID)
SELECT 'jilldocument', 'tiasHslWV7/ieEwGxos3LkNKvZLd/ben0qI3xXJrgjs=', 'pOijUhjnLLpoiyTTSeWq', 1, ID FROM USERS WHERE NAME = 'Jill Document';

INSERT INTO SECURITY_SUBJECT_ROLES(SUBJECT_ID, ROLE_ID)
SELECT SS.ID, SR.ID  FROM SECURITY_ROLES SR, SECURITY_SUBJECTS SS WHERE SR.NAME = 'drawingViewer' AND SS.USERNAME = 'jilldocument';

INSERT INTO SECURITY_SUBJECTS(USERNAME, PASSWORD, SALT, ENABLED, USER_ID)
SELECT 'bobbyd', 'tiasHslWV7/ieEwGxos3LkNKvZLd/ben0qI3xXJrgjs=', 'pOijUhjnLLpoiyTTSeWq', 1, ID FROM USERS WHERE NAME =  'Bobby D. Nothing';

INSERT INTO SECURITY_SUBJECT_ROLES(SUBJECT_ID, ROLE_ID)
SELECT SS.ID, SR.ID  FROM SECURITY_ROLES SR, SECURITY_SUBJECTS SS WHERE SR.NAME = 'doNothing' AND SS.USERNAME = 'bobbyd';

COMMIT;